# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{settings-tree}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Offirmo}]
  s.date = %q{2011-05-25}
  s.description = %q{This gem offers you a convenient settings structure for parameterizing your application.
Those settings are read from a YAML file.
Inheritance of settings (like in development modes) and multiple settings groups are available.
Great for a rails app but can be used for any ruby app.
}
  s.email = %q{offirmo.net@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/settings_tree.rb",
    "lib/settings_tree/settings_holder.rb",
    "settings-tree.gemspec",
    "spec/settings-tree_spec.rb",
    "spec/settings_holder_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_files/another_config.yml",
    "spec/test_files/config.yml",
    "spec/test_files/config_complement.yml"
  ]
  s.homepage = %q{http://github.com/Offirmo/settings-tree}
  s.licenses = [%q{CC0 1.0}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.3}
  s.summary = %q{Simple, arborescent settings structure from a YAML file.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<recursive-open-struct>, [">= 0"])
      s.add_runtime_dependency(%q<hash-deep-merge>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<recursive-open-struct>, [">= 0"])
      s.add_dependency(%q<hash-deep-merge>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<recursive-open-struct>, [">= 0"])
    s.add_dependency(%q<hash-deep-merge>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

